apiVersion: 1

datasources:
  - name: Stock Warehouse
    uid: stock-postgres
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      maxOpenConns: 25
      maxIdleConns: 25
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
